# Generated by Django 4.2.4 on 2024-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='crew',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
