# Generated by Django 4.2.4 on 2024-10-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ship_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='sailors',
            field=models.IntegerField(null=True),
        ),
    ]
